name: op3d
channels:
  - bottler
  - nvidia
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - defaults
dependencies:
  - cuda-nvcc=11.3.58
  - cudatoolkit=11.3.1
  - imageio=2.31.1
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numpy-base=1.24.3
  - nvidiacub=1.10.0
  - pillow=9.4.0
  - pooch=1.4.0
  - pycparser=2.21
  - python=3.8.17
  - pyyaml=6.0
  - tqdm=4.65.0
  - urllib3=1.26.16
  - yacs=0.1.8
  - yaml=0.2.5
  - zipp=3.11.0
  - pip:
      - chumpy==0.70
      - fvcore==0.1.5.post20221221
      - glfw==2.6.2
      - imageio-ffmpeg==0.4.8
      - imgui==2.0.0
      - importlib-metadata==6.8.0
      - iopath==0.1.10
      - itsdangerous==2.1.2
      - jinja2==3.1.2
      - kaolin==0.13.0
      - lpips==0.1.4
      - markdown==3.4.3
      - markupsafe==2.1.3
      - mrcfile==1.4.3
      - numpy==1.22.0
      - oauthlib==3.2.2
      - opencv-python==4.8.0.74
      - portalocker==2.7.0
      - protobuf==4.23.4
      - psutil==5.9.5
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pyopengl==3.1.7
      - pyspng==0.1.1
      - pytorch3d==0.7.4
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scipy==1.7.2
      - smplx==0.1.28
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.1
      - tensorboardx==2.6.1
      - torch==1.13.1+cu116
      - torchvision==0.14.1+cu116
      - tornado==6.1
      - usd-core==22.5.post1
      - werkzeug==2.3.6
